version: '3.8'

services:

  api:
  image: public.ecr.aws/f8e2v0r8/iic2173-g8-backend:latest
  ports:
    - "8000:8000"

  environment:
    # MQTT Variables
    - MQTT_HOST=${MQTT_HOST}
    - MQTT_PORT=${MQTT_PORT}
    - MQTT_USER=${MQTT_USER}
    - MQTT_PASSWORD=${MQTT_PASSWORD}

    # MongoDB Variables
    - MONGO_URL=${MONGO_URL}
    - MONGO_USERNAME=${MONGO_USERNAME}
    - MONGO_PASSWORD=${MONGO_PASSWORD}

    # Auth0 Variables
    - AUTH0_DOMAIN=${AUTH0_DOMAIN}
    - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
    - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
    - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}