version: '3.8'

services:
  api:
    image: public.ecr.aws/f8e2v0r8/iic2173-g8-backend:latest
    platform: linux/amd64
    command: [
      "gunicorn",
      "main:app",
      "--worker-class",
      "uvicorn.workers.UvicornWorker",
      "--workers",
      "3",
      "--bind",
      "0.0.0.0:8000",
    ]
    ports:
      - "8000:8000"
    environment:
      # MQTT Variables
      - MQTT_HOST=${MQTT_HOST}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      # MongoDB Variables
      - MONGO_URL=${MONGO_URL}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      # Auth0 Variables
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - FRONTEND_URL=https://web.e0futbol.me
      # Celery Variables
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - database
      - mqtt_listener
      - redis
      - worker

  worker:
    image: public.ecr.aws/f8e2v0r8/iic2173-g8-backend:latest
    platform: linux/amd64
    command: ["celery", "-A", "worker.celery_config", "worker", "--loglevel=info"]
    environment:
      # MQTT Variables
      - MQTT_HOST=${MQTT_HOST}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      # MongoDB Variables
      - MONGO_URL=${MONGO_URL}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      # Auth0 Variables
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      # Celery Variables
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - database

  flower:
    image: public.ecr.aws/f8e2v0r8/iic2173-g8-backend:latest
    platform: linux/amd64
    command: [
      "celery",
      "-A",
      "worker.celery_config.celery_app",
      "flower",
      "--port=5555",
    ]
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - worker

  mqtt_listener:
    image: public.ecr.aws/f8e2v0r8/iic2173-g8-backend:latest
    platform: linux/amd64
    environment:
      # MQTT Variables
      - MQTT_HOST=${MQTT_HOST}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      # MongoDB Variables
      - MONGO_URL=${MONGO_URL}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      # Auth0 Variables
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
    depends_on:
      - database

  database:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data: