services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: .
        target: /app
    depends_on:
      - database
      - mqtt_listener

  database:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: vicentelavagnino
      MONGO_INITDB_ROOT_PASSWORD: vicente1559
    ports:
      - "27017:27017"
    volumes:
      - type: volume
        source: mongo_data
        target: /data/db

  mqtt_listener:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: .
        target: /app
    depends_on:
      - database

volumes:
  mongo_data:
