name: Backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Checkout the repository
    - uses: actions/checkout@v2
    
    # 2. Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    # 3. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint black isort autopep8 pytest
    
    # 4. Format code with Black
    - name: Run Black formatter
      run: black .
    
    # 5. Sort imports with isort
    - name: Sort imports with isort
      run: isort .
    
    # 6. Format code with autopep8
    - name: Run autopep8
      run: autopep8 --in-place --aggressive --aggressive **/*.py
    
    # 7. Run linter with pylint
    - name: Run linter
      run: pylint **/*.py
    
    # 8. Run tests with pytest
    - name: Run tests
      run: pytest --junitxml=results.xml
    
    # 9. Archive test results (optional, to save test reports)
    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: results.xml
    
    # 10. Build Docker image (if you are using Docker)
    - name: Build Docker image
      run: docker build -t myapp-backend .
    
    # 11. Run Docker container (if you are using Docker)
    - name: Run Docker container
      run: docker run -d -p 8000:8000 myapp-backend
    
    # 12. Test API health (if you are using Docker)
    - name: Test API health
      run: |
        sleep 10  # Wait for the container to start
        curl http://localhost:8000 || exit 1
