name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -i ~/.ssh/new_keypair.pem -r ./ ec2-user@${{ secrets.EC2_IP }}:/home/ec2-user/app/

    - name: Restart the application on EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/new_keypair.pem ec2-user@${{ secrets.EC2_IP }} << 'EOF'
        cd /home/ec2-user/app/
        # Si es necesario, instala dependencias
        # pip install -r requirements.txt
        # Reinicia el servicio (puede ser con systemd o Docker)
        sudo systemctl restart myapp
        EOF
